### ISSUE TITLE
tidssone

### ISSUE THREAD

**Issue by jonasft** [aleksanb/timechallenge#24]
jeg er i norge -- når jeg skriver inn 09:15 så slås challengen opp klokken 10:15 fordi den bruker UTC+0

dette trenger noe fiks?!? har tenkt å bruke challenge hver dag i eksamensperioden OMG!

**Comment by stianjensen** [comment]
Ja, dette er litt problematisk. (Selv om det står i skjemaet at events blir lagd i UTC-0).
Vi oppdaget først at vi hadde tidssone-problemer da det også ble brukt av noen som var i USA i fjor. Da endret vi fra å alltid opprette i norsk tidssone til å bruke UTC+0 når man lager challenge, og vise i lokal tid etterpå.

Vi bør fikse challenge-skjemaet så det oppretter challenges i brukerens lokale tidssone i stedet. Bittelitt javascript-magi burde kunne fikse det.
