### ISSUE TITLE
Wrongly capitalized name in header

### ISSUE THREAD

**Issue by cristeahub** [aleksanb/timechallenge#7]
The name in the header isn't capitalized correctly.
![image](https://cloud.githubusercontent.com/assets/1488921/7371779/3c53b5a0-edc3-11e4-9eb7-2422cfc8eb23.png)

This is how the name looks in a challenge and how it should look in the header.
![image](https://cloud.githubusercontent.com/assets/1488921/7371788/5285c82c-edc3-11e4-8cfb-57f1efcca168.png)

**Comment by stianjensen** [comment]
Seems to be caused by the use of `capitalize`:

https://github.com/aleksanb/timechallenge/blob/master/app/views/layouts/_navbar.html.haml#L10

**Comment by cristeahub** [comment]
I think it would be better to do this capitalization in CSS with `capitalize`
